kind: Simple
apiVersion: k3d.io/v1alpha2
name: anshumank3d
# image: rancher/k3s:v1.20.4-k3s1
servers: 1
agents: 2
ports:
- port: 8080:80
  nodeFilters:
  - loadbalancer
- port: 4443:443
  nodeFilters:
  - loadbalancer
options:
  k3s:
    extraServerArgs:
    - --no-deploy=traefik